code: 131148
gijiroku: data/gijiroku.csv
giin: data/giin.csv
iinkai: data/iinkai.csv
years: data/years.csv
jogai: data/exclusion.csv
font: static/ShipporiMinchoB1-ExtraBold.ttf
target:
  place: 中野区
  start: 2001年2月
  end: 2022年12月
  url: https://kugikai-nakano.jp/search.html
developer:
  name: 岡村健一
  contact: https://twitter.com/Okamura_Kenichi
  img: static/developer.png